name: AutoBuild .NET

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Build
        run: dotnet build BetterOtherRoles/BetterOtherRoles.csproj --configuration Release

      - name: Upload BetterOtherRoles
        uses: actions/upload-artifact@v2
        with:
          name: BetterOtherRoles.dll
          path: BetterOtherRoles/bin/Release/net6.0/BetterOtherRoles.dll

